In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#fetch our data from the drive

df = pd.read_excel('/content/drive/My Drive/Dropoutdataset.xlsx')

In [ ]:
#confirm the uploaded dataset

df.head(3)

Marital status  Application mode  Application order  Course  \
0               1                 8                  5       2   
1               1                 6                  1      11   
2               1                 1                  5       5   

   Daytime/evening attendance  Previous qualification  Nacionality  \
0                           1                       1            1   
1                           1                       1            1   
2                           1                       1            1   

   Mother's qualification  Father's qualification  Mother's occupation  ...  \
0                      13                      10                    6  ...   
1                       1                       3                    4  ...   
2                      22                      27                   10  ...   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    0   
1                                    0                                    6   
2                                    0                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8   
1                                               0               13.9   
2                                               0               10.8   

   Inflation rate   GDP    Target  
0             1.4  1.74   Dropout  
1            -0.3  0.79  Graduate  
2             1.4  1.74   Dropout  

[3 rows x 35 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 35 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Marital status                                  4424 non-null   int64  
 1   Application mode                                4424 non-null   int64  
 2   Application order                               4424 non-null   int64  
 3   Course                                          4424 non-null   int64  
 4   Daytime/evening attendance                      4424 non-null   int64  
 5   Previous qualification                          4424 non-null   int64  
 6   Nacionality                                     4424 non-null   int64  
 7   Mother's qualification                          4424 non-null   int64  
 8   Father's qualification                          4424 non-null   int64  
 9   Mother's occupation                      

In [ ]:
#Checking for the null values by checking the sum

missing_values = df.isnull().sum()
missing_values

Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance                        0
Previous qualification                            0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrollment                                 0
International                                     0
Curricular u

In [ ]:
#check for unique values in the target column of our dataset

unique_value_Target = df ['Target'].unique()
unique_value_Target

array(['Dropout', 'Graduate', 'Enrolled'], dtype=object)

In [ ]:
#to confirm if the dataset is in panda format

type(df)

pandas.core.frame.DataFrame

In [ ]:
#Converting the dataset into a Numpy. (iloc -ilocation)

df = df.iloc[:,:].values
df

array([[1, 8, 5, ..., 1.4, 1.74, 'Dropout'],
       [1, 6, 1, ..., -0.3, 0.79, 'Graduate'],
       [1, 1, 5, ..., 1.4, 1.74, 'Dropout'],
       ...,
       [1, 1, 1, ..., -0.3, 0.79, 'Dropout'],
       [1, 1, 1, ..., -0.8, -3.12, 'Graduate'],
       [1, 5, 1, ..., 3.7, -1.7, 'Graduate']], dtype=object)

In [ ]:
#Encoding

from sklearn.preprocessing import LabelEncoder

In [ ]:
#Stored under the name Universoty

university = LabelEncoder ()

In [ ]:
#Apply LabelEncoder to the specific column 'Target'

df[:,34] = university.fit_transform(df[:, 34])
df

array([[1, 8, 5, ..., 1.4, 1.74, 0],
       [1, 6, 1, ..., -0.3, 0.79, 2],
       [1, 1, 5, ..., 1.4, 1.74, 0],
       ...,
       [1, 1, 1, ..., -0.3, 0.79, 0],
       [1, 1, 1, ..., -0.8, -3.12, 2],
       [1, 5, 1, ..., 3.7, -1.7, 2]], dtype=object)

In [ ]:
#use of one hot encoder all the features and target

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [ ]:
#Create a Transformer and name it as ct that will be used to encode categorical features of the dataset aand will pass through alll

ct = ColumnTransformer(transformers=[('encode', OneHotEncoder(), [34])], remainder = 'passthrough')

In [ ]:
X = df[:,0:34]
y = df[:,34]

In [ ]:
y = ct.fit_transform(df)

In [ ]:
Y = pd.DataFrame(y)

In [ ]:
Y.head(2)

0    1    2  3  4  5   6  7  8  9   ... 27 28 29 30 31         32 33  \
0  1.0  0.0  0.0  1  8  5   2  1  1  1  ...  0  0  0  0  0        0.0  0   
1  0.0  0.0  1.0  1  6  1  11  1  1  1  ...  0  0  6  6  6  13.666667  0   

     34   35    36  
0  10.8  1.4  1.74  
1  13.9 -0.3  0.79  

[2 rows x 37 columns]

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby(0).size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby(2).size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby(4).size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_3.groupby(5).size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp[2].value_counts()
    for x_label, grp in _df_4.groupby(0)
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel(0)
_ = plt.ylabel(2)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp[4].value_counts()
    for x_label, grp in _df_5.groupby(2)
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel(2)
_ = plt.ylabel(4)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp[5].value_counts()
    for x_label, grp in _df_6.groupby(4)
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel(4)
_ = plt.ylabel(5)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp[6].value_counts()
    for x_label, grp in _df_7.groupby(5)
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel(5)
_ = plt.ylabel(6)

In [ ]:
#splting the dataset into training and testing

from sklearn.model_selection import train_test_split
x_train, X_test, y_train, Y_test = train_test_split(X,y, test_size =0.2, random_state = 0)

In [ ]:
#fitting the regression model

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [ ]:
#Predicying the results

y_pred = regressor.predict(X_test)
y_pred

array([ 1.27053028e+00,  5.31372835e-02,  1.88365922e+00,  1.65409482e+00,
        7.72499975e-01,  1.35723222e+00,  1.26240294e+00,  1.80397623e+00,
        3.98278108e-01,  1.73874946e+00,  1.05060452e+00,  7.17269045e-02,
        7.77891565e-01,  1.09875846e+00,  7.83224940e-01,  1.92741225e+00,
        1.02418850e+00,  2.61272550e-01,  1.73359411e+00,  1.25186193e+00,
        3.19334183e-01,  1.76283666e+00,  1.46281373e+00,  1.69254161e+00,
        1.24097957e+00,  2.02496687e-01,  1.26766645e+00, -2.46147653e-02,
        1.72672747e+00,  1.40067660e+00,  3.77685885e-01,  7.47608805e-01,
        1.93038424e+00,  1.63813503e+00,  1.32228462e+00,  1.65279520e+00,
        1.76404396e+00,  1.68993704e+00,  1.02871587e+00, -2.10022489e-01,
        1.55331612e+00,  2.54401025e-01,  1.70913834e+00,  1.86556961e+00,
        1.89963159e+00,  7.92348765e-01,  7.87769843e-01,  1.78703001e+00,
        1.48727196e+00,  1.86001527e+00, -5.24718264e-03,  9.16010211e-02,
        1.19577640e+00,  

In [ ]:
#Calculate the R squared value

from sklearn.metrics import r2_score
r2_score(Y_test, y_pred)

0.6125253548639076